name: CancelFriendRequest
version: ${project.version}
author: Simonsator
depends: [ PartyAndFriends ]
main: de.simonsator.partyandfriends.cfr.CFRMain
description: An add-on for party and friends to cancel friend requests